### PR TITLE
added gradient button

### PR DESCRIPTION
**Pull request by Apps4Jjt**

### CODE REVIEW

**Review by pratikbutani — CHANGES_REQUESTED** [review]
Empty file is not allowed.

**Comment by Apps4Jjt** [comment]
@pratikbutani

**Comment by julienKeyvalue** [comment]
Accidentally forgot to add the file while commiting @pratikbutani . its fixed in the above commit

**Comment by Apps4Jjt** [comment]
Accidentally forgot to add contents to the file. fixed the issue in the above commit

**Review by pratikbutani — APPROVED** [review]

**Pull request merged**
